"""add 's' in booking

Revision ID: 0973912b2cba
Revises: 7df857c4ad72
Create Date: 2025-02-17 14:30:44.665036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0973912b2cba"
down_revision: Union[str, None] = "7df857c4ad72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("booking")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("room_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date_from", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("date_to", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], name="booking_room_id_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="booking_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="booking_pkey"),
    )
    op.drop_table("bookings")
    # ### end Alembic commands ###
